# cloudformation for EC2 instance
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an EC2 instance'
Parameters:
  ImageId:
    Type: 'AWS::EC2::Image::Id'
    Description: 'AMI for your instance'
    Default: 'ami-0e54eba7c51c234f6'
  InstanceType:
    Type: 'String'
    Description: 'Instance type'
    Default: 't2.micro'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-instance'